// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcOYM6EJ58F3rfu4NLVi70OejoiHD0Is0',
    appId: '1:755379200261:web:91c56afce534b2e32a576c',
    messagingSenderId: '755379200261',
    projectId: 'siklab-project',
    authDomain: 'siklab-project.firebaseapp.com',
    storageBucket: 'siklab-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChj3Y8h6QTeZowpMOl2c9Y2iAZQDSJf9o',
    appId: '1:755379200261:android:a512a7b9539dbd832a576c',
    messagingSenderId: '755379200261',
    projectId: 'siklab-project',
    storageBucket: 'siklab-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5_Tzr9hLkYTNCRmCfTskwRYcmhe6gYRA',
    appId: '1:755379200261:ios:244d0cb90ec7db152a576c',
    messagingSenderId: '755379200261',
    projectId: 'siklab-project',
    storageBucket: 'siklab-project.appspot.com',
    androidClientId: '755379200261-kn5ifas5mfh4h98i1keh02r61upr8ope.apps.googleusercontent.com',
    iosClientId: '755379200261-uf8vh591j7inctvjjfu7fd3j7djtdbht.apps.googleusercontent.com',
    iosBundleId: 'com.example.siklabproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5_Tzr9hLkYTNCRmCfTskwRYcmhe6gYRA',
    appId: '1:755379200261:ios:244d0cb90ec7db152a576c',
    messagingSenderId: '755379200261',
    projectId: 'siklab-project',
    storageBucket: 'siklab-project.appspot.com',
    androidClientId: '755379200261-kn5ifas5mfh4h98i1keh02r61upr8ope.apps.googleusercontent.com',
    iosClientId: '755379200261-uf8vh591j7inctvjjfu7fd3j7djtdbht.apps.googleusercontent.com',
    iosBundleId: 'com.example.siklabproject',
  );
}
